TRUNCATE TABLE order_items;
TRUNCATE TABLE customer_phone_numbers;
TRUNCATE TABLE phone_numbers CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE products CASCADE;
TRUNCATE TABLE customers CASCADE;
